feat(readme): add archival message
GlobalX/pockybot pull request #439
Opened 2020-07-20 06:43 UTC by jimcullenaus

2020-07-20 07:41 UTC, Evangelinexx requested changes

2020-07-20 07:41 UTC, Evangelinexx commented on README.md
> +The `pockybot` project has been supersede by [PockyBot.Net](https://github.com/GlobalX/PockyBot.NET).
```suggestion
The `pockybot` project has been superseded by [PockyBot.Net](https://github.com/GlobalX/PockyBot.NET).
```

2020-07-20 22:38 UTC, Lauraducky approved these changes

2020-07-21 23:03 UTC, AmreenC approved these changes

2020-07-21 23:15 UTC, Evangelinexx approved these changes

2020-07-22 00:21 UTC, merged

2020-07-22 00:25 UTC, Evangelinexx commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/pockybot/v/1.6.0)
- [GitHub release](https://github.com/GlobalX/pockybot/releases/tag/v1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: